# Generated by Django 6.0.5 on 2026-05-19 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('customer', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('enquiry', 'Enquiry'), ('quoted', 'Quoted'), ('order_received', 'Order Received'), ('survey_required', 'Survey Required'), ('confirmed', 'Confirmed'), ('in_production', 'In Production'), ('ready_to_deliver', 'Ready to Deliver'), ('delivered', 'Delivered'), ('installation_scheduled', 'Installation Scheduled'), ('installed', 'Installed'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='enquiry', max_length=30)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('requires_installation', models.BooleanField(default=False)),
                ('installation_notes', models.TextField(blank=True, help_text='Details about the installation')),
                ('rams_required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
