# Generated by Django 6.0.5 on 2026-05-20 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='installation_notes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='requires_installation',
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='drawing_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='installation_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='installation_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='rams_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='sales_order',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('enquiry', 'Enquiry'), ('quoted', 'Quoted'), ('order_received', 'Order Received'), ('processed', 'Processed'), ('sent_for_picking', 'Sent for Picking'), ('ready_to_deliver', 'Ready to Deliver'), ('delivered', 'Delivered'), ('installation_scheduled', 'Installation Scheduled'), ('installed', 'Installed'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='enquiry', max_length=30),
        ),
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
