# Generated by Django 6.0.5 on 2026-05-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_customer_remove_project_installation_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='installation_date_type',
            field=models.CharField(choices=[('exact', 'Exact Date'), ('month', 'Month')], default='exact', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='installation_month',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='project',
            name='installation_month_part',
            field=models.CharField(blank=True, choices=[('', 'Any'), ('early', 'Early'), ('mid', 'Mid'), ('end', 'End')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='project',
            name='installation_same_as_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
