# Generated by Django 6.0.5 on 2026-05-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_installation_date_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, help_text='Short description shown on dashboard', max_length=300),
        ),
    ]
