# Generated by Django 6.0.5 on 2026-05-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_description_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('enquiry', 'Enquiry'), ('quoted', 'Quoted'), ('order_received', 'Order Received'), ('processed', 'Processed'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='enquiry', max_length=30),
        ),
    ]
