# Generated by Django 6.0.5 on 2026-05-22 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_product_pickinglist_pickinglistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickinglistitem',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='pickinglistitem',
            name='item_type',
            field=models.CharField(choices=[('stock', 'Stock Item'), ('ns', 'Non-Stock Item'), ('message', 'Message / Note')], default='stock', max_length=10),
        ),
        migrations.AddField(
            model_name='pickinglistitem',
            name='message',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pickinglistitem',
            name='ns_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pickinglistitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pickinglistitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='picking_items', to='projects.product'),
        ),
        migrations.AlterField(
            model_name='pickinglistitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
