# Generated by Django 6.0.5 on 2026-05-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_pickinglistitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_allocated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_on_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
