# Generated by Django 6.0.5 on 2026-05-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_pickingtemplate_pickingtemplateitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='important_notes',
            field=models.TextField(blank=True),
        ),
    ]
