# Generated by Django 6.0.5 on 2026-05-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_materialprice_projectcost_projectcostline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcostline',
            name='line_type',
            field=models.CharField(choices=[('frame', 'Frame'), ('shelf', 'Shelf'), ('stock', 'Stock Item'), ('ns', 'Non-Stock'), ('inhang', 'In. Hanging'), ('outhang', 'Out. Hanging'), ('wipe', 'Wipe Board'), ('mesh', 'Mesh Panel'), ('loadsign', 'Load Sign'), ('toptie', 'Top Tie')], max_length=10),
        ),
    ]
