# Generated by Django 6.0.5 on 2026-05-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_projectcostline_line_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UprightAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='projectcost',
            name='accessories',
            field=models.ManyToManyField(blank=True, to='projects.uprightaccessory'),
        ),
    ]
