# Generated by Django 6.0.5 on 2026-05-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_seed_upright_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcost',
            name='wall_fixings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
