# Generated by Django 6.0.5 on 2026-05-25 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_projectcost_wall_fixings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.uprightaccessory')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_overrides', to='projects.projectcost')),
            ],
            options={
                'unique_together': {('cost', 'accessory')},
            },
        ),
    ]
