# Generated by Django 6.0.5 on 2026-05-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_accessoryoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='file_mime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='file_original_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_docs/'),
        ),
    ]
