# Generated by Django 6.0.5 on 2026-05-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('tag', 'Tagged in comment'), ('message', 'New message'), ('reminder', 'Reminder')], max_length=20),
        ),
    ]
