# Generated by Django 6.0.5 on 2026-05-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationreport',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='installationreport',
            name='fitting_crew',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='installationreport',
            name='job_tasks',
            field=models.TextField(blank=True, help_text='Schedule of works / job tasks for satisfaction note'),
        ),
        migrations.AddField(
            model_name='installationreport',
            name='return_visit_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installationreport',
            name='site_cleared',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installationreport',
            name='site_cleared_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='installationreport',
            name='site_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='installationreport',
            name='work_completed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installationreport',
            name='work_completed_notes',
            field=models.TextField(blank=True),
        ),
    ]
