# Generated by Django 6.0.5 on 2026-05-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_installationreport_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationreport',
            name='fitting_crew_phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
