# Generated by Django 6.0.5 on 2026-05-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_installationreport_fitting_crew_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='addr_county',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
