# Generated by Django 6.0.5 on 2026-05-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_fittingcrew'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcost',
            name='back_to_back_fixings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='mobile_base_sets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
