# Generated by Django 4.2.30 on 2026-06-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_purchaseorder_supplier_stockmovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='item_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('ns', 'Non-Stock'), ('message', 'Message')], default='stock', max_length=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address_line1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address_line2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='town',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
