# Generated by Django 4.2.30 on 2026-06-03 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0034_purchaseorderline_item_type_supplier_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickinglist',
            name='allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickinglist',
            name='allocated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickinglist',
            name='allocated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picking_lists_allocated', to=settings.AUTH_USER_MODEL),
        ),
    ]
