# Generated by Django 4.2.30 on 2026-06-04 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_pickinglist_allocated_pickinglist_allocated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('received', 'Received (PO)'), ('received_undo', 'Receipt Reversed'), ('allocated', 'Allocated'), ('deallocated', 'Allocation Released'), ('dispatched', 'Dispatched / Sent'), ('adjust', 'Manual Adjustment')], default='adjust', max_length=20),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='projects.project'),
        ),
    ]
