# Generated by Django 4.2.30 on 2026-06-04 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0036_stockmovement_movement_type_stockmovement_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='FittingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file_data', models.BinaryField(blank=True, null=True)),
                ('file_mime', models.CharField(blank=True, max_length=100)),
                ('file_original_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='fitting_notes', to='projects.product')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
