# Generated by Django 4.2.30 on 2026-06-04 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_customerprofile_address_line1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True)),
                ('capacity', models.TextField(blank=True)),
                ('bay_breakdown', models.TextField(blank=True)),
                ('spec_note', models.TextField(blank=True)),
                ('main_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('main_price_label', models.CharField(default='Our price to supply, deliver and install:', max_length=200)),
                ('extra_label', models.CharField(blank=True, max_length=200)),
                ('extra_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lead_time', models.CharField(blank=True, max_length=200)),
                ('payment_terms', models.CharField(blank=True, max_length=200)),
                ('terms_text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='projects.project')),
            ],
        ),
    ]
