# Generated by Django 4.2.30 on 2026-06-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_projectquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquote',
            name='supply_line',
            field=models.TextField(blank=True),
        ),
    ]
