# Generated by Django 4.2.30 on 2026-06-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_projectquote_supply_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquote',
            name='address_block',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectquote',
            name='header_ref',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='projectquote',
            name='quote_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
