# Generated by Django 4.2.30 on 2026-06-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_projectquote_address_block_projectquote_header_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcostline',
            name='product_line',
            field=models.CharField(choices=[('trimline', 'Trimline'), ('longspan', 'Longspan')], default='trimline', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectcostline',
            name='line_type',
            field=models.CharField(choices=[('frame', 'Frame'), ('shelf', 'Shelf'), ('stock', 'Stock Item'), ('ns', 'Non-Stock'), ('inhang', 'In. Hanging'), ('outhang', 'Out. Hanging'), ('wipe', 'Wipe Board'), ('mesh', 'Mesh Panel'), ('loadsign', 'Load Sign'), ('toptie', 'Top Tie'), ('beams', 'Beams'), ('extras', 'Extras'), ('ls_frame', 'LS Frame'), ('ls_shelf', 'LS Shelf'), ('ls_trolley', 'LS Trolley')], max_length=12),
        ),
    ]
