# Generated by Django 4.2.30 on 2026-06-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_projectcostline_product_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquote',
            name='closing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectquote',
            name='greeting',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='projectquote',
            name='signature_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='projectquote',
            name='thank_you',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reportphoto',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportphoto',
            name='file_mime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reportphoto',
            name='file_original_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='satisfactionnote',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satisfactionnote',
            name='file_mime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='satisfactionnote',
            name='file_original_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reportphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='report_photos/'),
        ),
        migrations.AlterField(
            model_name='satisfactionnote',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='satisfaction_notes/'),
        ),
    ]
