# Generated by Django 4.2.30 on 2026-06-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_projectquote_closing_projectquote_greeting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_line', models.CharField(default='longspan', max_length=10)),
                ('category', models.CharField(choices=[('ls_frame', 'Longspan Frame'), ('ls_shelf', 'Longspan Shelf Level'), ('ls_trolley', 'Longspan Trolley'), ('trimline', 'Trimline'), ('other', 'Other')], default='ls_frame', max_length=20)),
                ('code', models.CharField(blank=True, max_length=60)),
                ('label', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product_line', 'category', 'sort_order', 'label'],
            },
        ),
    ]
