# Generated by Django 4.2.30 on 2026-06-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_pricelistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
