# Generated by Django 4.2.30 on 2026-06-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_pricelistitem_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistitem',
            name='category',
            field=models.CharField(choices=[('ls_frame', 'Longspan Frame'), ('ls_shelf', 'Longspan Shelf Level'), ('ls_trolley', 'Longspan Trolley'), ('trimline', 'Trimline'), ('other', 'Other')], default='ls_frame', max_length=60),
        ),
    ]
