# Generated by Django 4.2.30 on 2026-06-09 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0046_alter_pricelistitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('codes', models.TextField(blank=True, help_text='Comma or space separated product codes')),
                ('file_data', models.BinaryField(blank=True, null=True)),
                ('file_mime', models.CharField(blank=True, max_length=100)),
                ('file_original_name', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='projectquote',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='quotes', to='projects.quotephoto'),
        ),
    ]
