# Generated by Django 4.2.30 on 2026-06-09 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_quotephoto_projectquote_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquote',
            name='photo_columns',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='QuoteAttachedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_data', models.BinaryField(blank=True, null=True)),
                ('file_mime', models.CharField(blank=True, max_length=100)),
                ('file_original_name', models.CharField(blank=True, max_length=200)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_photos', to='projects.projectquote')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
