# Generated by Django 4.2.30 on 2026-06-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_projectquote_photo_columns_quoteattachedphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='country',
            field=models.CharField(blank=True, default='United Kingdom', max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='addr_country',
            field=models.CharField(blank=True, default='United Kingdom', max_length=60),
        ),
    ]
