# Generated by Django 4.2.30 on 2026-06-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_customerprofile_country_project_addr_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='email2',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='email3',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='eori_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='vat_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
