# Generated by Django 4.2.30 on 2026-06-10 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_customerprofile_email2_customerprofile_email3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.CharField(blank=True, max_length=100)),
                ('invoice_to', models.TextField(blank=True)),
                ('delivery_to', models.CharField(blank=True, default='AS INVOICE', max_length=300)),
                ('ezr_contact', models.CharField(blank=True, max_length=200)),
                ('po_number', models.CharField(blank=True, max_length=100)),
                ('requisitioner', models.CharField(blank=True, max_length=100)),
                ('shipped_via', models.CharField(blank=True, max_length=100)),
                ('fob_point', models.CharField(blank=True, max_length=100)),
                ('terms', models.CharField(blank=True, default='PRO-FORMA', max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('goods_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_pct', models.PositiveSmallIntegerField(default=50)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proforma', to='projects.project')),
            ],
        ),
    ]
