# Generated by Django 6.0.6 on 2026-06-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_proformainvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fittingnote',
            name='templates',
            field=models.ManyToManyField(blank=True, related_name='fitting_notes', to='projects.pickingtemplate'),
        ),
        migrations.AddField(
            model_name='pickinglist',
            name='templates_used',
            field=models.ManyToManyField(blank=True, related_name='used_in_picking_lists', to='projects.pickingtemplate'),
        ),
    ]
