# Generated by Django 6.0.6 on 2026-06-16 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_fittingnote_templates_pickinglist_templates_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='qty_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('enquiry', 'Enquiry'), ('quoted', 'Quoted'), ('order_received', 'Order Received'), ('processed', 'Processed'), ('part_delivered', 'Part Delivered'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='enquiry', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('confirmed', 'Confirmed'), ('part_received', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('delivered_on', models.DateField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_phases', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
