# Generated by Django 6.0.6 on 2026-06-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_purchaseorderline_qty_received_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
