# Generated by Django 6.0.6 on 2026-06-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_purchaseorder_locked_purchaseorder_locked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='carriage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='del_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='del_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='del_county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='del_line1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='del_line2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='del_postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
