# Generated by Django 6.0.6 on 2026-06-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_purchaseorder_carriage_purchaseorder_del_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='del_company',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
