# Generated by Django 6.0.6 on 2026-06-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_purchaseorder_del_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='acknowledged_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
