# Generated by Django 6.0.6 on 2026-06-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_purchaseorder_acknowledged_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='account_number',
            field=models.CharField(blank=True, help_text='Sage customer account reference', max_length=100),
        ),
    ]
