# Generated by Django 4.2.30 on 2026-07-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_customerprofile_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='ack_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quote_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
