# Generated by Django 4.2.30 on 2026-07-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_purchaseorder_ack_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
