# Generated by Django 4.2.30 on 2026-07-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_fix_corrupted_mentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='colour',
            field=models.CharField(blank=True, help_text='Hex colour for avatar', max_length=7),
        ),
    ]
