# Generated by Django 4.2.30 on 2026-07-15 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_staffprofile_colour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcost',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='cost',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proforma', to='projects.projectcost'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='label',
            field=models.CharField(default='Option A', max_length=100),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectquote',
            name='cost',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='projects.projectcost'),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proformas', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='projectcost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='projectquote',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='projects.project'),
        ),
    ]
