# Generated by Django 4.2.30 on 2026-07-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0070_migrate_quote_proforma_to_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('account', 'On Account'), ('proforma', 'Proforma'), ('bacs', 'BACs'), ('chaps', 'CHAPs'), ('sagepay', 'Sagepay'), ('paypal', 'PayPal'), ('cc', 'CC'), ('dc', 'DC'), ('chq', 'CHQ'), ('cash', 'Cash'), ('cod', 'COD')], max_length=20),
        ),
    ]
