# Generated by Django 4.2.30 on 2026-07-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_project_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='kg, used for delivery weight estimates', max_digits=8, null=True),
        ),
    ]
