# Generated by Django 4.2.30 on 2026-07-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0072_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('1', '1 Discontinued'), ('2', '2 Board'), ('3', '3 Type 1'), ('4', '4 Trimline'), ('5', '5 Type 1 & Trimline common'), ('6', '6 AR Longspan'), ('7', '7 AR Pallet Rack'), ('8', '8 Misc Fixings'), ('9', '9 JWW products'), ('10', '10 Wire & Mesh'), ('11', '11 Misc Metal'), ('12', '12 Ladders & Steps'), ('13', '13 Lockers & Cupboards'), ('14', '14 Box & Bin - Plastic'), ('15', '15 Box & Bin - Cardboard'), ('16', '16 Misc Out Sourced'), ('17', '17 Misc Non Product Item'), ('18', '18 Written Off')], max_length=2),
        ),
    ]
