# Generated by Django 4.2.30 on 2026-07-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0073_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='can_view_reports',
            field=models.BooleanField(default=False, help_text='Can view Sales Summary and Daily Accounts Report, independent of Staff status'),
        ),
    ]
