# Generated by Django 4.2.30 on 2026-07-24 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0074_staffprofile_can_view_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickingtemplate',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Set manually — templates often include bespoke items, so this is not auto-summed from Stock prices', max_digits=10),
        ),
        migrations.AddField(
            model_name='projectcostline',
            name='picking_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_lines', to='projects.pickingtemplate'),
        ),
        migrations.AlterField(
            model_name='projectcostline',
            name='line_type',
            field=models.CharField(choices=[('frame', 'Frame'), ('shelf', 'Shelf'), ('stock', 'Stock Item'), ('ns', 'Non-Stock'), ('inhang', 'In. Hanging'), ('outhang', 'Out. Hanging'), ('wipe', 'Wipe Board'), ('mesh', 'Mesh Panel'), ('loadsign', 'Load Sign'), ('toptie', 'Top Tie'), ('beams', 'Beams'), ('extras', 'Extras'), ('ls_frame', 'LS Frame'), ('ls_shelf', 'LS Shelf'), ('ls_trolley', 'LS Trolley'), ('template', 'Picking Template')], max_length=12),
        ),
    ]
