# Generated by Django 4.2.30 on 2026-07-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0075_picking_template_costing'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('works_order', 'Works Order'), ('site_signage', 'Site Signage'), ('ledger', 'Ledger')], default='default', help_text='Personal visual style — set on your own profile', max_length=20),
        ),
    ]
