# Generated by Django 4.2.30 on 2026-07-27 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0076_staffprofile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer_profile',
            field=models.ForeignKey(blank=True, help_text='Real link to the Customer record. The customer text field is kept in sync automatically for backward compatibility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.customerprofile'),
        ),
    ]
