# Generated by Django 4.2.30 on 2026-07-27 10:28

from django.db import migrations


def backfill_links(apps, schema_editor):
    """Link each Project to a real CustomerProfile wherever the project's
    existing customer text exactly matches (case/whitespace-insensitive) a
    CustomerProfile name already on file. Projects with no clean match are
    left unlinked — safer than guessing or creating placeholder records for
    what might just be a typo or a one-off name."""
    Project = apps.get_model('projects', 'Project')
    CustomerProfile = apps.get_model('projects', 'CustomerProfile')

    profiles_by_name = {cp.name.strip().lower(): cp for cp in CustomerProfile.objects.all()}
    linked = 0
    for project in Project.objects.filter(customer_profile__isnull=True).exclude(customer=''):
        key = project.customer.strip().lower()
        profile = profiles_by_name.get(key)
        if profile:
            project.customer_profile = profile
            project.save(update_fields=['customer_profile'])
            linked += 1
    print(f'  Linked {linked} project(s) to an existing CustomerProfile by exact name match.')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0077_project_customer_profile_link'),
    ]

    operations = [
        migrations.RunPython(backfill_links, noop_reverse),
    ]
