# Generated by Django 4.2.30 on 2026-07-27 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0078_backfill_customer_profile_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_data', models.BinaryField(blank=True, null=True)),
                ('file_mime', models.CharField(blank=True, max_length=100)),
                ('file_original_name', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('price_list', 'Price List'), ('brochure', 'Brochure'), ('other', 'Other')], default='price_list', max_length=20)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Year this price list/brochure applies to, if relevant', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.supplier')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
