# Generated by Django 4.2.30 on 2026-07-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_product_supplier_price_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='company_reg_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='name',
            field=models.CharField(help_text='Not required to be unique — imports may intentionally create duplicates to be reconciled by hand', max_length=200),
        ),
    ]
