# Generated by Django 4.2.30 on 2026-07-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0081_customerprofile_import_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
