# Generated by Django 4.2.30 on 2026-07-30 10:34

from django.db import migrations


def update_price(apps, schema_editor):
    UprightAccessory = apps.get_model('projects', 'UprightAccessory')
    updated = UprightAccessory.objects.filter(code='SMFOOT').update(unit_price=1.50)
    print(f'  Updated {updated} SM Footplates record(s) to £1.50')


def revert_price(apps, schema_editor):
    UprightAccessory = apps.get_model('projects', 'UprightAccessory')
    UprightAccessory.objects.filter(code='SMFOOT').update(unit_price=2.50)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0082_customerprofile_is_active'),
    ]

    operations = [
        migrations.RunPython(update_price, revert_price),
    ]
