# Generated by Django 4.2.30 on 2026-07-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0083_update_sm_foot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcostline',
            name='no_deck',
            field=models.BooleanField(default=False),
        ),
    ]
