# Generated by Django 4.2.30 on 2026-07-31 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0084_projectcostline_no_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='e.g. invoice number IV-141486', max_length=100)),
                ('currency', models.CharField(choices=[('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='CAD', max_length=3)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('USD', 'US Dollar')], max_length=3, unique=True)),
                ('rate_to_gbp', models.DecimalField(decimal_places=6, help_text='1 unit of this currency = this many GBP', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
