# Generated by Django 4.2.30 on 2026-07-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0085_exchangerate_goodsintransit'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockValuationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('board_stock', 'Board Stock'), ('non_stock', 'Non Stock (delivered)')], default='board_stock', max_length=20)),
                ('date_changed', models.CharField(blank=True, help_text='When this price was last changed/checked, as recorded on the spreadsheet', max_length=60)),
                ('po_reference', models.CharField(blank=True, help_text='The PO that last changed this price', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_gbp', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('cost_eur', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('cost_cad', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_gbp', models.DecimalField(blank=True, decimal_places=2, help_text='Total as recorded on the spreadsheet — 0/blank for non-GBP items whose conversion is computed live instead', max_digits=14, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
