# Generated by Django 4.2.30 on 2026-08-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0087_import_stock_valuation_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockvaluationitem',
            name='linked_product',
            field=models.ForeignKey(blank=True, help_text='When set, Quantity is pulled live from this Stock item instead of the imported snapshot value', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.product'),
        ),
    ]
