# Generated by Django 4.2.30 on 2026-08-03 14:40

# Generated migration to auto-link stock valuation items to matching Stock
# codes, so Quantity can be pulled live instead of the static import value.

from django.db import migrations


def autolink(apps, schema_editor):
    StockValuationItem = apps.get_model('projects', 'StockValuationItem')
    Product = apps.get_model('projects', 'Product')
    linked = 0
    for item in StockValuationItem.objects.filter(category='board_stock', linked_product__isnull=True):
        prod = Product.objects.filter(code__iexact=item.description.strip()).first()
        if prod:
            item.linked_product = prod
            item.save(update_fields=['linked_product'])
            linked += 1
    print(f'  Auto-linked {linked} stock valuation item(s) to matching Stock codes')


def reverse_autolink(apps, schema_editor):
    StockValuationItem = apps.get_model('projects', 'StockValuationItem')
    StockValuationItem.objects.update(linked_product=None)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0088_stockvaluationitem_linked_product'),
    ]

    operations = [
        migrations.RunPython(autolink, reverse_autolink),
    ]
