# Generated by Django 4.2.30 on 2026-08-05 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0090_customer_contacts_notes_lost_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManualPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('po_number', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_pos', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
