# Generated by Django 4.2.30 on 2026-08-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0091_projectmanualpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='blocked_reason',
            field=models.CharField(blank=True, help_text='Why this is blocked, e.g. waiting on customer, drawing sign-off, site not ready', max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Flagged as stalled/at risk'),
        ),
        migrations.AddField(
            model_name='projectmanualpo',
            name='date_delivery',
            field=models.DateField(blank=True, help_text='Date to be delivered', null=True),
        ),
        migrations.AddField(
            model_name='projectmanualpo',
            name='date_ordered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
