# Generated by Django 4.2.30 on 2026-08-07 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0093_supplier_contact_todo_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(blank=True, max_length=200)),
                ('line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='United Kingdom', max_length=60)),
                ('fao', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to='projects.customerprofile')),
                ('source_project', models.ForeignKey(blank=True, help_text='The project this address was first captured from, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
