# Generated by Django 4.2.30 on 2026-08-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0094_customer_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='recommended_markup',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recommended markup % — shown as a reference when costing a job for this customer', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='recommended_payment_terms',
            field=models.CharField(blank=True, help_text='e.g. 30 days, Pro forma, 50% deposit', max_length=100),
        ),
    ]
