# Generated by Django 4.2.30 on 2026-08-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0096_quote_share_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='doc_type',
            field=models.CharField(choices=[('drawing', 'Drawing'), ('quote', 'Quote'), ('contract', 'Contract'), ('rams', 'RAMS'), ('survey', 'Survey'), ('photo', 'Photo'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
