# Generated by Django 4.2.30 on 2026-08-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0097_alter_projectdocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcost',
            name='accepted_by_name',
            field=models.CharField(blank=True, help_text='Name and role entered when accepting online', max_length=200),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='accepted_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='accepted_online',
            field=models.BooleanField(default=False, help_text='Accepted via the customer-facing share link, rather than by staff internally'),
        ),
        migrations.AddField(
            model_name='projectcost',
            name='accepted_online_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
