# Generated by Django 4.2.30 on 2026-08-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0098_quote_online_acceptance_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('tag', 'Tagged in comment'), ('message', 'New message'), ('reminder', 'Reminder'), ('quote_accepted', 'Quote accepted online')], max_length=20),
        ),
    ]
