# Generated by Django 4.2.30 on 2026-08-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0099_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesharelink',
            name='is_retired',
            field=models.BooleanField(default=False, help_text='Superseded by a newer link generated for the same quote'),
        ),
    ]
