# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0100_quote_share_link_retired'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcost',
            name='mobile_base_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
