# Generated by Django 4.2.30 on 2026-09-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0101_projectcost_mobile_base_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcost',
            name='mobile_base_unit_price',
        ),
    ]
