# Generated by Django 4.2.30 on 2026-09-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0102_remove_projectcost_mobile_base_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='photo_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='photo_mime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teammessage',
            name='photo_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammessage',
            name='photo_mime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teammessage',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
