# Generated by Django 4.2.30 on 2026-09-18 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0103_message_photo_data_message_photo_mime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thumbs_up_by',
            field=models.ManyToManyField(blank=True, related_name='thumbs_up_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammessage',
            name='thumbs_up_by',
            field=models.ManyToManyField(blank=True, related_name='thumbs_up_team_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
